apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: djapp
    env: prod
    tier: backend
    owner: Daniil
  name: djapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: djapp
    spec:
      containers:
        - name: web
          image: traderdaniil/k8s-djangoapp:v5
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: djsecret
          ports:
            - containerPort: 80
              name: http
