apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      containers:
      - name: migratej
        image: traderdaniil/k8s-djangoapp:v5
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: djsecret
        command: ["python", "manage.py", "migrate"]
      restartPolicy: Never
  backoffLimit: 4