apiVersion: batch/v1
kind: CronJob
metadata:
  name: session
spec:
  schedule: "* 10 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 50
      template:
        spec:
          containers:
          - name: sessiondj
            image: traderdaniil/k8s-djangoapp:v5
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: djsecret
            command:
            - /bin/sh
            - -c
            - python manage.py clearsessions
          restartPolicy: OnFailure
          activeDeadlineSeconds: 200