apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: djapp
    env: prod
    tier: backend
    owner: Daniil
  name: djapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: djapp
    spec:
      containers:
        - name: web
          image: traderdaniil/k8s-djangoapp:v5
          imagePullPolicy: IfNotPresent
          env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: djsecret
                key: secret_key
          - name: ALLOWED_HOSTS
            valueFrom:
              secretKeyRef:
                name: djsecret
                key: allowed_hosts
          - name: DEBUG
            valueFrom:
              secretKeyRef:
                name: djsecret
                key: debug
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: djsecret
                key: database_url
          ports:
            - containerPort: 80
              name: http
