apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      containers:
      - name: migratej
        image: traderdaniil/k8s-djangoapp:v5
        imagePullPolicy: IfNotPresent
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: djsecret
              key: secret_key
        - name: ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              name: djsecret
              key: allowed_hosts
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              name: djsecret
              key: debug
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: djsecret
              key: database_url
        command: ["python", "manage.py", "migrate"]
      restartPolicy: Never
  backoffLimit: 4